version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Creating lib directory..."
      - mkdir -p lib
      - echo "Python version:"
      - python --version
      - echo "Pip version:"
      - pip --version
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib --verbose
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip .
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name getDataFromAPI --zip-file fileb://deployment_package.zip
      - echo "DONE!!"