version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 deployment_package.zip DB_Manager_EP
      - zip -g -r9 deployment_package.zip table_objects
      - zip -g -r9 deployment_package.zip requirements.txt
      - zip -g -r9 deployment_package.zip lambda_function.py
      - zip -g -r9 deployment_package.zip events_handler.py
      - zip -g -r9 deployment_package.zip utils.py
      
      - echo "Adding config_file.json to the deployment package..."
      - if [ -f "config_file.json" ]; then echo "config_file.json file exists"; else echo "config_file.json file does not exist"; fi
      - zip -g -r9 deployment_package.zip config_file.json

  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name getDataFromAPI --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
