version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      # First Package: Packaging everything except 'table_objects' and call it get_api_lambda_pack
      - echo "Packaging Lambda function 1 (get_api_lambda_pack)..."
      - mkdir get_api_lambda_pack
      # Zip everything except the 'table_objects' directory
      - zip -r9 get_api_lambda_pack.zip api_data_extraction DB_Manager_EP requirements.txt lambda_function_get_api_data.py config_file.json

      # Second Package: Packaging everything
      - echo "Packaging Lambda function 2 (all files)..."
      - mkdir load_raw_data_lambda_pack
      # Zip the entire directory including all files and folders
      - zip -r9 load_raw_data_lambda_pack.zip data_sources DB_Manager_EP requirements.txt lambda_function_raw_data.py config_file.json

      # third Package: Packaging everything
      - echo "Packaging Lambda function 3 (all files)..."
      - mkdir full_lambda_package
      # Zip the entire directory including all files and folders
      - zip -r9 full_lambda_package.zip data_sources DB_Manager_EP table_objects requirements.txt lambda_function_db.py config_file.json
      -
      # fourth Package: Packaging everything
      - echo "Packaging Lambda function 3 (all files)..."
      - mkdir scoring_package
      # Zip the entire directory including all files and folders
      - zip -r9 scoring_package.zip DB_Manager_EP table_objects data_enrichment lambda_function_post_scoring.py config_file.json

  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name getDataFromAPI --zip-file fileb://get_api_lambda_pack.zip
      - echo "DONE!!"

      - echo "Updating lambda Function 2..."
      - aws lambda update-function-code --function-name LoadRawData --zip-file fileb://load_raw_data_lambda_pack.zip
      - echo "DONE!!"

      - echo Deploying Lambda function 3...
      - aws lambda update-function-code --function-name BiDataProcessLevel --zip-file fileb://full_lambda_package.zip
      - echo "DONE!!"

      - echo Deploying Lambda function 4...
      - aws lambda update-function-code --function-name PostScoring --zip-file fileb://scoring_package.zip
      - echo "DONE!!"